/data/pijarj/BC-ORG-Data/Code
Input Notebook:  fMRI_Prep_Tutorial.ipynb
Output Notebook: fMRI_Prep_Papermill_2.ipynb
Executing:   0%|          | 0/25 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   4%|▍         | 1/25 [00:05<02:08,  5.36s/cell]Executing:  16%|█▌        | 4/25 [00:25<02:16,  6.49s/cell]Executing:  20%|██        | 5/25 [00:28<01:50,  5.50s/cell]Executing:  28%|██▊       | 7/25 [00:30<01:01,  3.41s/cell]Executing:  36%|███▌      | 9/25 [00:30<00:34,  2.14s/cell]Executing:  48%|████▊     | 12/25 [00:30<00:15,  1.18s/cell]Executing:  64%|██████▍   | 16/25 [00:30<00:05,  1.53cell/s]Executing:  72%|███████▏  | 18/25 [00:30<00:03,  1.92cell/s]Executing:  80%|████████  | 20/25 [00:31<00:02,  2.39cell/s]Executing:  84%|████████▍ | 21/25 [00:49<00:01,  2.39cell/s]Autosave too slow: 2.68 sec, over 25% limit. Backing off to 10 sec
Autosave too slow: 3.43 sec, over 25% limit. Backing off to 20 sec
Kernel died while waiting for execute reply.
Executing:  88%|████████▊ | 22/25 [17:47<07:04, 141.57s/cell]Executing:  88%|████████▊ | 22/25 [17:48<02:25, 48.56s/cell] 
Traceback (most recent call last):
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 107, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/engines.py", line 359, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/engines.py", line 418, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/data/pijarj/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/data/pijarj/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 845, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
Executing:  88%|████████▊ | 22/25 [2:24:41<57:35, 1151.78s/cell]Executing:  92%|█████████▏| 23/25 [2:24:41<32:14, 967.24s/cell] Executing: 100%|██████████| 25/25 [2:24:41<00:00, 663.49s/cell]Executing: 100%|██████████| 25/25 [2:24:43<00:00, 347.32s/cell]
